############# English navigation ##############

# main menu
[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "About Us"
pageRef = "/about"
weight = 2

[[main]]
name = "Services"
pageRef = "/services"
weight = 3

[[main]]
parent = "Services"
name = "Custom Web Development"
pageRef = "/services/web-development"
weight = 1

[[main]]
parent = "Services"
name = "Cybersecurity Consulting"
pageRef = "/services/cybersecurity"
weight = 2

[[main]]
parent = "Services"
name = "IT Strategy Consulting"
pageRef = "/services/it-strategy"
weight = 3

[[main]]
parent = "Services"
name = "Performance Optimization"
pageRef = "/services/performance-optimization"
weight = 4

[[main]]
parent = "Services"
name = "Secure Hosting Solutions"
pageRef = "/services/secure-hosting"
weight = 5

[[main]]
weight = 4
name = "Blog"
pageRef = "/blog"

[[main]]
weight = 5
name = "Contact"
pageRef = "/contact"

# footer menu
[[footer]]
name = "FAQ"
pageRef = "/faq"
weight = 1

[[footer]]
name = "Privacy Policy"
pageRef = "/privacy-policy"
weight = 2

[[footer]]
name = "Terms of Service"
pageRef = "/terms"
weight = 3
